name: Auto-label PR by branch
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  label:
    permissions:
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const head = context.payload.pull_request.head.ref; // e.g., agent/claude/feature-x
            const m = head.match(/^agent\/([a-z0-9_-]+)\//i);
            if (!m) return;
            const agent = m[1].toLowerCase();
            const label = `agent:${agent}`;
            // Ensure label exists (create if missing)
            try {
              await github.request('POST /repos/{owner}/{repo}/labels', {
                owner: context.repo.owner, repo: context.repo.repo,
                name: label, color: 'BFD4F2', description: 'PR authored by agent'
              });
            } catch (e) {
              // ignore if already exists
            }
            await github.request('POST /repos/{owner}/{repo}/issues/{issue_number}/labels', {
              owner: context.repo.owner, repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              labels: [label]
            });
